Gen protos

diff --git a/dev/generate b/dev/generate
--- a/dev/generate
+++ b/dev/generate
@@ -3,4 +3,8 @@ set -e
 
 go generate ./...
 
-mockgen -package api github.com/xmtp/proto/v3/go/mls/api/v1 MlsApi_SubscribeGroupMessagesServer,MlsApi_SubscribeWelcomeMessagesServer > pkg/mls/api/v1/mock.gen.go
+mockgen -package api github.com/xmtp/xmtp-node-go/pkg/proto/mls/api/v1 MlsApi_SubscribeGroupMessagesServer,MlsApi_SubscribeWelcomeMessagesServer > pkg/mls/api/v1/mock.gen.go
+if ! buf generate https://github.com/xmtp/proto.git#branch=main,subdir=proto; then
+    echo "Failed to generate protobuf definitions"
+    exit 1
+fi
